name:                advent-of-code2022
version:             0.1.0.0
github:              "TiagoVentosa/advent-of-code-2022"
license:             BSD3
author:              "Tiago Ventosa"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent-of-code-2022#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- mtl


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  advent-of-code2022-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code2022

tests:
  spec:
    defaults: hspec/hspec@main
    dependencies:
      - QuickCheck
      - hspec-megaparsec
      - advent-of-code2022
